version: 2.1
orbs:
  # https://github.com/CircleCI-Public/config-preview-sdk/blob/master/docs/using-orbs.md#semantic-versioning-in-orbs
  cypress: cypress/cypress@volatile

workflows:
  run-e2e-tests:
    jobs:
      - cypress/install
      - cypress/e2e:
          record: false
