version: 2.1
orbs:
  cypress: cypress/cypress@dev:0.0.1
workflows:
  build:
    jobs:
      # checks out code and installs dependencies once
      - cypress/install:
          build: "npm run build"
      # runs on 3 machines, load balances tests
      # and records on Cypress Dashboard
      - cypress/run-3x:
          requires:
            - cypress/install
          group: "3x"
          start: "npm run server"
