version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
executors:
  with-chrome:
    resource_class: small
    docker:
      - image: "cypress/browsers:node14.16.0-chrome90-ff88"
# workflows:
#   build:
#     jobs:
      # - cypress/install:
      #      build: "npm run build"
            # - cypress/run:
      #       spec: "cypress/integration/*.js"
            # group: 'all tests' # name this group "all tests" on the dashboard
            # start: 'npm start' # start server before running tests
workflows:
  build:
    jobs:
      - cypress/install
    
      - cypress/run:
          name: Chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          group: all tests
          executor: with-chrome
          browser: chrome
          spec: cypress/integration/*            
      - cypress/run:
          name: ConsoleGitBash
          requires:
            - cypress/install
          spec: "cypress/integration/*.js"      