version: 2.1
orbs:
  cypress: cypress/cypress@dev:0.0.1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/parallel-2x:
          group: "2x"
      - cypress/parallel-3x:
          group: "3x"
