version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0 #versao
executors:
  with-chrome:
    resource_class: xlarge
    docker:
      - image: "cypress/browsers:node16.5.0-chrome94-ff93"  #"cypress/browsers:node14.16.0-chrome90-ff88" 
# workflows:
#   build:
#     jobs:
      # - cypress/install:
      #      build: "npm run build"
            # - cypress/run:
      #       spec: "cypress/integration/*.js"
            # group: 'all tests' # name this group "all tests" on the dashboard
            # start: 'npm start' # start server before running tests
workflows:
  build:
    jobs:
      - cypress/install
    
      - cypress/run:
          name: Chrome - teste
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73
          group: 'all tests'
          browser: chrome
          spec: "cypress/integration/*.js"            

      - cypress/run:
          name: Electron - teste
          requires:
            - cypress/install
          spec: "cypress/integration/*.js"     

      - cypress/run:
          name: 1-Integracao - Chome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          group: 'all tests'
          browser: chrome
          spec: "cypress/integration/1-Integracao/*"

      - cypress/run:
          name: 2-Estoque - Chome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          group: 'all tests'
          browser: chrome
          spec: cypress/integration/2-Estoque/*

      - cypress/run:
          name: 3-Compras - Chome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          group: 'all tests'
          browser: chrome
          spec: cypress/integration/3-Compras/* 

      - cypress/run:
          name: 5-Faturamento - Chome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          group: 'all tests'
          browser: chrome
          spec: cypress/integration/5-Faturamento/*

      - cypress/run:
          name: 6-Financeiro - Chome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          group: 'all tests'
          browser: chrome
          spec: cypress/integration/6-Financeiro/* 

      - cypress/run:
          name: 7-Serviço - Chome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          group: 'all tests'
          browser: chrome
          spec: cypress/integration/7-Serviço/* 
